/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://he4722q3vnawjocpjxusuojrte.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_cognito_identity_pool_id": "us-east-1:a6862963-36b0-488b-945d-46b649946bad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8dQMU1mC0",
    "aws_user_pools_web_client_id": "3v4agaomavj2854b6fcnh4db78",
    "oauth": {}
};


export default awsmobile;
